### ISSUE TITLE
Add Ethereum Syllabus Resource

### ISSUE THREAD

**Issue by LCBradley3k** [btomashvili/awesome-ethereum#3]
One of the top posts in the [Ethereum subreddit](https://www.reddit.com/r/ethereum/) was the [in-depth Ethereum guide](https://www.reddit.com/r/ethereum/comments/7jj1so/rethereum_i_wrote_this_to_explain_ethereum_in/).

After contacting the writer, we worked together to format it properly into an [Ethereum syllabus](https://novicedock.com/learn/cryptocurrency/ethereum), where each section has a detailed summary, and resources to go learn the part. 

It gives new learners a path to follow that provided some overall context.

I think it would make a great addition to the list :) 
Feel free to add it if you agree

**Comment by btomashvili** [comment]
added
